# Question 1

In [2]:
import pandas as pd
df = pd.read_csv("food_db.csv")
print("Number of rows and columns:", df.shape)
df

Number of rows and columns: (10, 5)

   food_id            name discount   price     rating
0        1  Butter Chicken      10%  $12.99  Excellent
1        2     Masala Dosa       5%   $7.50       Good
2        3         Biryani      15%  $15.99  Excellent
3        4           Chaat      20%   $3.99    Average
4        5         Samosas      10%   $2.50       Good
5        6   Chole Bhature       5%   $8.99  Excellent
6        7    Paneer Tikka      10%  $10.99  Very Good
7        8     Idli-Sambar      15%   $6.99       Good
8        9      Rogan Josh      10%  $16.99  Excellent
9       10           Lassi       5%   $3.50    Average

# Question 2

In [4]:

# Replace 5% and 10% with 13%
new_df = df.replace({
    'discount': {
        '5%': '13%',
        '10%': '13%'
    }
})


new_df

   food_id            name discount   price     rating
0        1  Butter Chicken      13%  $12.99  Excellent
1        2     Masala Dosa      13%   $7.50       Good
2        3         Biryani      15%  $15.99  Excellent
3        4           Chaat      20%   $3.99    Average
4        5         Samosas      13%   $2.50       Good
5        6   Chole Bhature      13%   $8.99  Excellent
6        7    Paneer Tikka      13%  $10.99  Very Good
7        8     Idli-Sambar      15%   $6.99       Good
8        9      Rogan Josh      13%  $16.99  Excellent
9       10           Lassi      13%   $3.50    Average

## Question 3

In [5]:

rating_map = {
    'Excellent': 4,
    'very Good': 3,
    'Good': 2,
    'Average': 1
}

new_df = df.replace({'rating': rating_map})
new_df

   food_id            name discount   price     rating
0        1  Butter Chicken      10%  $12.99          4
1        2     Masala Dosa       5%   $7.50          2
2        3         Biryani      15%  $15.99          4
3        4           Chaat      20%   $3.99          1
4        5         Samosas      10%   $2.50          2
5        6   Chole Bhature       5%   $8.99          4
6        7    Paneer Tikka      10%  $10.99  Very Good
7        8     Idli-Sambar      15%   $6.99          2
8        9      Rogan Josh      10%  $16.99          4
9       10           Lassi       5%   $3.50          1